-- MySQL Script generated by MySQL Workbench
-- Tue Dec  1 21:46:35 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema job-vacancy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema job-vacancy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `job-vacancy` DEFAULT CHARACTER SET utf8 ;
USE `job-vacancy` ;

-- -----------------------------------------------------
-- Table `job-vacancy`.`companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `job-vacancy`.`companies` (
  `idCompany` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(65) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `postalCode` VARCHAR(45) NOT NULL,
  `permission` VARCHAR(45) NOT NULL DEFAULT 'company',
  PRIMARY KEY (`idCompany`),
  UNIQUE INDEX `idcompany_UNIQUE` (`idCompany` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `job-vacancy`.`candidates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `job-vacancy`.`candidates` (
  `idCandidates` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(65) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `postalCode` VARCHAR(45) NOT NULL,
  `age` INT NOT NULL,
  `genre` VARCHAR(1) NOT NULL,
  `interest` VARCHAR(45) NOT NULL,
  `permission` VARCHAR(45) NOT NULL DEFAULT 'candidate',
  PRIMARY KEY (`idCandidates`),
  UNIQUE INDEX `idcompany_UNIQUE` (`idCandidates` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `job-vacancy`.`vacancies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `job-vacancy`.`vacancies` (
  `idVacancy` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `salary` DECIMAL(15,2) NOT NULL,
  `interest` VARCHAR(45) NOT NULL,
  `maxCandidates` INT NOT NULL,
  `candidates` INT NOT NULL,
  PRIMARY KEY (`idVacancy`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `job-vacancy`.`candidates_vacancy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `job-vacancy`.`candidates_vacancy` (
  `idCandidates` INT NOT NULL,
  `idVacancy` INT NOT NULL,
  PRIMARY KEY (`idCandidates`, `idVacancy`),
  INDEX `idVacancy_idx` (`idVacancy` ASC),
  CONSTRAINT `idCandidates`
    FOREIGN KEY (`idCandidates`)
    REFERENCES `job-vacancy`.`candidates` (`idCandidates`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idVacancy`
    FOREIGN KEY (`idVacancy`)
    REFERENCES `job-vacancy`.`vacancies` (`idVacancy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `job-vacancy`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `job-vacancy`.`messages` (
  `idmessages` INT NOT NULL,
  `idCandidate` INT NOT NULL,
  `idCompany` INT NOT NULL,
  `message` VARCHAR(255) NOT NULL,
  `date` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idmessages`),
  UNIQUE INDEX `idmessages_UNIQUE` (`idmessages` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
